# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Incidentally
tagline:          Adventures in computing and life
url:              https://github.com/jbytheway
paginate:         1
baseurl:          /
author:
  name:           John Bytheway
#  url:            https://...
#  email:          ...@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jbytheway/jbytheway.github.io
