# Dependencies
# Comment these out to just use the defaults
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Incidentally
tagline:          Adventures in computing and life
url:              https://jbytheway.github.io
baseurl:          /
author:
  name:           John Bytheway
#  url:            https://...
#  email:          ...@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jbytheway/jbytheway.github.io
